### ISSUE TITLE
Align left hand of teams page to the selector 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Wordpress#60]
![flush-community-page](https://cloud.githubusercontent.com/assets/3667179/5795117/35970ca0-9f56-11e4-9c6e-5180d1d387c8.png)

- The left hand of this page should align to the left hand teams selector.  
- The user icons are too big. Is there something wrong with the filter? I think they should be either the same size as the icons to the right, or smaller. Can you check the code here to see what it is?
- The user profiles are continually getting blurry. Can you look into why this is continually happening?

**Comment by nowned** [comment]
-Left hand of the page is aligned!
-They are the same size now!
-Blurry profile images always seem to be caused by people who's images are auto pulling from Gravatar. I've set it to force pull the right size from Gravatar, but sometimes people have uploaded small photos there and it's already too small to be resized that large. Sadly nothing to be done about that!
